### ISSUE TITLE
Extra txt importation

### ISSUE THREAD

**Issue by THMprod** [Galladite27/ONScripter-EN#40]
Hello, i'm looking to try to make a VN with your onscripter-en but i'm not really good to managing my project with the 00.txt 01.txt, etc. 
I want to know if we have an import command or something like that to my game go looking for a script file with an other name.
I'm just reading the documentation on your website and i don't found something for this.

**Comment by Galladite27** [comment]
Hi there, I don't think there is a way to do this. You can set a specific folder to check for script files using the "root" option in [ons.cfg](https://kaisernet.org/onscripter/#optlist), but the files have to follow that format.

However, you can compile multiple files of any name into one obfuscated script file (by default, nscript.dat - make sure to [change](https://github.com/galladite27/onscripter-en?tab=readme-ov-file#utf-8-mode) if using UTF-8 or proportional fonts) using `nscmake 0.txt my.txt files.txt etc.txt`. You can get this, as well as other tools for manipulating files used by *NScripter, [here](https://galladite.net/~galladite/nscripter/resources/onscripter/tools%20%28builds%29/). If you're constantly testing your game, you could make it even easier by using a Makefile such as this:

```
files=scripts/0.txt scripts/my.txt scripts/functions.txt
out=nscript.dat

all: $(out)

$(out): $(files)
	nscmake -o $(out) $(files)

run: $(out)
	./onscripter-en

clean:
	rm $(out)

.PHONY: all run clean

```

Then just run "make run" to rebuild and test it. Code not tested.

**Comment by THMprod** [comment]
Oh thx, I will try it in this week :)
